import = [
    # uncomment the flavour you want below:
    # "~/.config/alacritty/catppuccin-latte.toml"
    # "~/.config/alacritty/catppuccin-frappe.toml"
    # "~/.config/alacritty/catppuccin-macchiato.toml"
    # "~/.config/alacritty/catppuccin-mocha.toml"
    #
    #    "~/.config/alacritty/flexoki.toml",
      "~/.config/alacritty/rose-pine.toml"
  #    "~/.config/alacritty/rose-pine-moon.toml"
]

[shell]
program = "tmux"

[window]
opacity =  0.9
decorations = "Buttonless"

[window.padding]
x = 8
y = 8

[env]
TERM = "xterm-256color"


[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

